# Generated by Django 4.1.5 on 2023-01-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_specialsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialsale',
            old_name='couponcode',
            new_name='coupon_code',
        ),
        migrations.RenameField(
            model_name='specialsale',
            old_name='discountpercentage',
            new_name='discount_percentage',
        ),
    ]
