# Generated by Django 4.0.5 on 2023-02-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('Opens', models.CharField(max_length=20)),
                ('Closes', models.CharField(max_length=20)),
            ],
        ),
    ]
