# Generated by Django 4.1.5 on 2023-01-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_couponcode_specialsale_coupon_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='Image_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='Stock',
        ),
        migrations.RenameField(
            model_name='specialsale',
            old_name='coupon_code',
            new_name='CouponCode',
        ),
        migrations.RenameField(
            model_name='specialsale',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='specialsale',
            old_name='discount_percentage',
            new_name='Discount',
        ),
    ]
