# Generated by Django 4.1.5 on 2023-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_url_product_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('Image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
